stages:
  - test
  - package

variables:
  COMPOSER_MEMORY_LIMIT: -1

# Matrix of PHP versions
.test_template: &test_definition
  image: php:$PHP_VERSION-cli
  before_script:
    - apt-get update && apt-get install -y unzip git curl
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - composer install --prefer-dist --no-interaction
    - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests

test_php56:
  <<: *test_definition
  stage: test
  variables:
    PHP_VERSION: "5.6"
  tags:
    - docker

test_php74:
  <<: *test_definition
  stage: test
  variables:
    PHP_VERSION: "7.4"
  tags:
    - docker

test_php82:
  <<: *test_definition
  stage: test
  variables:
    PHP_VERSION: "8.2"
  tags:
    - docker

package_library:
  stage: package
  image: php:7.4-cli
  only:
    - tags  # Only package on version tags like v1.0.0
  before_script:
    - apt-get update && apt-get install -y unzip git curl
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - composer install --prefer-dist --no-interaction
    - composer validate
    - zip -r account-validator-${CI_COMMIT_TAG}.zip src tests composer.json README.md
  artifacts:
    paths:
      - account-validator-${CI_COMMIT_TAG}.zip
    expire_in: 1 week
  tags:
    - docker
