name: PHP Library CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'    # trigger on version tags like v1.0.0
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [5.6, 7.4, 8.2]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Install dependencies
        run: composer install
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests

  package:
    name: Package Library
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Install dependencies
        run: composer install
      - name: Build / Publish Package
        run: |
          # Here you can zip the package or publish to GitHub Packages
          composer validate
          composer package
      - name: Upload Package as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: account-validator
          path: ./   # adjust if you want to zip specific folder
