name: PHP Library CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [5.6, 7.4, 8.2]
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Validate PHP
        run: php -v

      - name: Validate Composer version
